In [1]:
import numpy as np
# 1
a_1 = np.arange(1, 11)
print(a_1)
a_1 = np.linspace(1, 10, num=10)
print(a_1)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [2]:
# 2
a_2 = np.zeros((3, 3), dtype=float)
print(a_2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# 3
a_3 = np.random.randint(1, 10, size=(5, 5))
print(a_3)

[[3 1 2 4 9]
 [5 5 2 5 4]
 [8 9 8 8 3]
 [1 2 8 4 8]
 [6 4 3 8 8]]


In [4]:
# 4
a_4 = np.random.random((4, 4))
print(a_4)

[[0.00145928 0.24722829 0.82017451 0.68445448]
 [0.81000758 0.60728818 0.04681688 0.67826219]
 [0.13635135 0.04679199 0.31701697 0.2491402 ]
 [0.65056545 0.40287065 0.16276953 0.30987923]]


In [5]:
# 5
a_5_1 = np.random.randint(1, 10, 5)
a_5_2 = np.random.randint(1, 10, 5)
print(a_5_1, a_5_2)
sum_v = a_5_1 + a_5_2
print(sum_v)
subtraction_v = a_5_1 - a_5_2
print(subtraction_v)
multiply_v = a_5_1 * a_5_2
print(multiply_v)
division_v = a_5_1 / a_5_2
print(division_v)

[3 8 8 6 9] [3 9 1 1 4]
[ 6 17  9  7 13]
[ 0 -1  7  5  5]
[ 9 72  8  6 36]
[1.         0.88888889 8.         6.         2.25      ]


In [6]:
# 6
a_6_1 = np.random.randint(100, size=7)
a_6_2 = np.random.randint(100, size=7)
print(a_6_1)
print(a_6_2)
scalar_mult = np.dot(a_6_1, a_6_2)
print(scalar_mult)

[16 97 22 18 78 57 54]
[12 56 53 82 38 24 85]
17188


In [7]:
# 7
m1 = np.random.randint(1, 10, (2, 2))
m2 = np.random.randint(1, 10, (2, 3))
mult = np.dot(m1, m2)
print(mult)

[[33 31 26]
 [71 60 41]]


In [8]:
# 8
m1 = np.random.randint(1, 10, (3, 3))
m1_inv = np.linalg.inv(m1)
print(m1_inv)

[[ 0.         -0.22727273  0.31818182]
 [ 0.2         0.07272727 -0.18181818]
 [-0.2         0.2        -0.        ]]


In [10]:
# 9
m1 = np.random.random((4, 4))
print(m1)
m1_t = m1.T
print(m1_t)

[[0.47167632 0.18431261 0.47707374 0.72024982]
 [0.07284127 0.68091046 0.58543594 0.87664238]
 [0.10130825 0.59761547 0.9224926  0.97762863]
 [0.57855307 0.45355187 0.00554214 0.97207353]]
[[0.47167632 0.07284127 0.10130825 0.57855307]
 [0.18431261 0.68091046 0.59761547 0.45355187]
 [0.47707374 0.58543594 0.9224926  0.00554214]
 [0.72024982 0.87664238 0.97762863 0.97207353]]


In [11]:
# 10
m1 = np.random.randint(1, 10, (3, 4))
v1 = np.random.randint(1, 10, size=4)
mult = np.dot(m1, v1)
print(mult)

[125 127 108]


In [12]:
# 11
m1 = np.random.random((2, 3))
v1 = np.random.random(3)
mult = np.dot(m1, v1)
print(mult)

[1.00702655 1.41897819]


In [13]:
# 12
m1 = np.random.randint(1, 10, (2, 2))
m2 = np.random.randint(1, 10, (2, 2))
mult = m1 * m2
print(mult)

[[ 9 28]
 [24 28]]


In [14]:
# 13
m1 = np.random.randint(1, 10, (2, 2))
m2 = np.random.randint(1, 10, (2, 2))
mult = np.dot(m1, m2)
print(mult)

[[37 50]
 [23 32]]


In [15]:
# 14
m1 = np.random.randint(1, 100, (5, 5))
sum_el = m1.sum()
print(sum_el)

1113


In [16]:
# 15
m1 = np.random.randint(1, 10, (4, 4))
m2 = np.random.randint(1, 10, (4, 4))
sub = m1 - m2
print(sub)

[[ 5 -5  4  1]
 [ 2  4  0 -1]
 [ 4 -1  3 -1]
 [ 5  2 -2 -1]]


In [17]:
# 16
m1 = np.random.random((3, 3))
print(np.sum(m1, axis=1))

[2.66282373 1.3939919  0.77294968]


In [18]:
# 17
m1 = np.random.randint(100, size=(3, 4))
print(m1)
print(np.square(m1))

[[68 93 17 45]
 [64  3 67 47]
 [45 39 92 60]]
[[4624 8649  289 2025]
 [4096    9 4489 2209]
 [2025 1521 8464 3600]]


In [19]:
# 18
v1 = np.random.randint(1, 50, size=4)
print(v1)
print(np.sqrt(v1))

[16  3  2 12]
[4.         1.73205081 1.41421356 3.46410162]
